name: Run Lyla Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: تحميل الملفات
        uses: actions/checkout@v4

      - name: تشغيل Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: تثبيت المتطلبات
        run: pip install -r requirements.txt

      - name: تشغيل البوت
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python bot.py
